import Navbar from "@/src/components/navbar/navbar";
import Footer from "@/src/components/footer/footer";

import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// This is used to set the title and description of the page (useful for Search Engine Optimisation (SEO))
export const metadata = {
  title: '<Name of website>',
  description: 'Generated by create next app', // Default description
}

// Defines the structure of the root layout for the entire application.
export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body className={inter.className}>
        <Navbar className="fixed-navbar" />
        <main className="main-content">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
